config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get :search, to: 'search#index'

  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}

  get 'comment/create'
  get 'comment/destroy'
  get 'comment/update'
  concern :votable do
    member do
      post :vote_count_up
      post :vote_count_down
    end
  end

  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end


  root to: "questions#index"
  resources :questions, concerns: [:votable, :commentable ] do
    resources :answers, concerns: [:votable, :commentable ], shallow: true do
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end

    end
  end

  resources :subscriptions, only: [:create, :destroy]
  resources :attachments, only: :destroy


  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true
class Question < ApplicationRecord
  include Votable
  include Attachable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  after_create :subscribe_author!

  validates :title, :body, presence: true

  private

  def subscribe_author!
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: :show
  authorize_resource

  def index
    @questions = Question.all
    respond_with @questions, each_serializer: QuestionCollectionSerializer
  end

  def show
    respond_with @question
  end

  def create
    respond_with(current_resource_owner.questions.create(question_params))
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except:  %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  after_action :publish_question, only: :create
  before_action :build_answer, only: :show
  before_action :load_subscription, only: %i[show update]

  respond_to :html
  respond_to :js, only: :update
  authorize_resource

  def index
    @questions = Question.paginate(page: params[:page], per_page: 10).order('created_at DESC')
  end

  def show
    respond_with(@question)
  end

  def new
    respond_with(@question = current_user.questions.build)
  end

  def edit; end

  def create
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update

    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    respond_with(@question.destroy) if current_user.author?(@question)
  end

  private

  def build_answer
    @answer = @question.answers.build
  end

  def publish_question
    logger.debug "Question attributes hash: #{@question.attributes.inspect}"
    return if @question.errors.any? || @question.nil?
    ActionCable.server.broadcast(
        'questions',
        ApplicationController.render(
          partial: 'questions/question_for_cable',
          locals: { question: @question }
        )
    )
  end

  def load_question
    @question = Question.find(params[:id])
    gon.question_id = @question.id
  end

  def load_subscription
    @subscription = current_user.subscriptions.where(question: @question).first if current_user
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with model: @question do |form|
  = render 'shared/errors', resource: @question
  .form-group
    = form.label :title
    = form.text_field :title, class: 'form-control'
  .form-group
    = form.label :body
    = form.text_area :body, class: 'form-control'
  .form-group
    p Attachments:
    = form.fields_for :attachments, @question.attachments.build do |a|
      = render 'shared/attachments_fields_for', f: a
  .links
    = link_to_add_association 'Add file', form, :attachments, partial: 'shared/attachments_fields_for'
  .form-group
    = form.submit 'Create', class: 'btn btn-primary'

app/views/questions/_question.html.slim
.question-block
  .card.bg-default
    .card-header
      .row
        .col-md-4
          .question-info-block
            | Created by: #{@question.user.fullname} at #{@question.created_at.to_formatted_s(:short)}
      .row
        .col-md-10
          - cache @question do
            h3 = @question.title unless @question.nil?
        .col-md-1
          .btn-group-vertical
            - if can?(:update, @question)
              = link_to 'Edit Question', '', class: "edit-question-link btn btn-outline-primary btn-sm", data: {question: @question.id}
            - if can?(:destroy, @question)
              = link_to 'Delete Question', question_path(@question), method: :delete, data: {confirm: "Are you sure?"},
                      class: 'btn btn-outline-danger btn-sm'


      .row
        .col-md-2
          .subscriptions
            - if current_user&.subscribed?(@question) && can?(:destroy, @question)
              = render 'subscriptions/unsubscribe', subscription: @subscription
            - else
              - if can?(:create, Subscription)
                = render 'subscriptions/subscribe', question: @question
    .card-body
      .row
        .col-md-11.question-body
          h5 = @question.body
          = render 'shared/attachments', resource: @question unless @question.attachments.empty?
          .edit-question-form
            = form_with model: @question, remote: true do |form|
              .form-group
                = form.label :title
                = form.text_field :title, class: 'form-control'
              .form-group
                = form.label :body
                = form.text_area :body, class: 'form-control'
              .form-group
                = form.submit 'Save', class: 'btn btn-primary'

        .col-md-1
          .vote_counter
            = @question.votes_sum
          .vote_links
            = render 'shared/vote_links', resource: @question
      .row
        .col-md-12
          div class="comments_for_question_#{@question.id} comments"
            - if can?(:create, Comment)
              = link_to 'Add Comment', '', class: "comment-link_for_question_#{@question.id} comment-link btn btn-primary", data: {resource_id: @question.id, resource_type: "question"}

            = render 'comments/form', resource: @question

            p Comments
            = render @question.comments

app/views/questions/_question_for_cable.html.slim
.question id="question_#{question.id}"
  .card.bg-default
    .h5.card-header
      = link_to "#{question.title}", question_path(question)
    .card-body
      p.card-text
        = question.body

app/views/questions/edit.html.slim
= render 'form'

app/views/questions/index.html.slim
.row.justify-content-right
  - if can?(:create, Question)
    p= link_to 'Ask question', new_question_path, class: 'btn btn-primary'
.questions-list
  - unless @questions.empty?

    - @questions.each do |question|
      .row
        .col-md-12
          .question.mt-4 id="question_#{question.id}"
            .card.bg-default
              .h5.card-header
                = link_to "#{question.title}", question_path(question)
              .card-body
                p.card-text
                  = question.body.truncate(250)
  = will_paginate @questions, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/questions/new.html.slim
.row.justify-content-center
  .col-md-6
    .card.bg-default
      .h5.card-header Ask new auestion
      .card-body
        = render 'form'

app/views/questions/show.html.slim
= render @question

.answers.mt-4
  = render @question.answers.best_ordered

.row.justify-content-center.mt-6.answer-block-form
  .col-md-8.float-center
    .card
      .card-header.form-title.text-center
        h3 You know Answer ?
      .card-block
        - if can?(:create, Answer)
          .form-block
            .errors
            = form_with model: [@question, @answer], class: 'new_answer', remote: true do |form|
              = render 'shared/errors', resource: @answer
              .form-group
                = form.label :body, 'Your answer'
                = form.text_area :body, class: 'form-control'
              .form-group
                = form.fields_for :attachments, @answer.attachments.build do |a|
                  = render 'shared/attachments_fields_for', f: a
              .links
                = link_to_add_association 'Add file', form, :attachments, partial: 'shared/attachments_fields_for'
              .form-group
                = form.submit 'Answer the question', class: 'btn btn-primary'

app/views/questions/update.js.erb
$('#error').remove();
<% if @question.errors.any? %>
<% @question.errors.full_messages.each do |message| %>
$('.edit-question-form').append('<div id="error"><%= j message %></div>');
<% end %>
<% else %>
$('.edit-question-form').hide();
$('.question-block').html('<%= j render @question %>');
<% end %>