config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get :search, to: 'search#index'

  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}

  get 'comment/create'
  get 'comment/destroy'
  get 'comment/update'
  concern :votable do
    member do
      post :vote_count_up
      post :vote_count_down
    end
  end

  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end


  root to: "questions#index"
  resources :questions, concerns: [:votable, :commentable ] do
    resources :answers, concerns: [:votable, :commentable ], shallow: true do
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end

    end
  end

  resources :subscriptions, only: [:create, :destroy]
  resources :attachments, only: :destroy


  mount ActionCable.server => '/cable'
end

app/views/shared/_attachments.html.slim
.attachments id="#{resource.id}"
  p Attachments:
  ul
    - resource.attachments.each do |a|
      - cache a do
        li id="attachment-#{a.id}"
          = link_to a.file.identifier, a.file.url
      - if can?(:destroy, a)
        = link_to 'Delete File', a, remote: true, method: :delete, data: { id: resource.id } if current_user&.author?(resource)

app/views/shared/_attachments_fields_for.html.slim
.attached-fields
  = f.label :file
  = f.file_field :file, class: 'form-control-file'

app/views/shared/_errors.html.slim
-if resource.present? && resource.errors.any?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.id} do
    =  "Errors: #{resource.errors.count}"
    - resource.errors.full_messages.each do |message|
      div class="alert alert-danger" = message

app/views/shared/_nav.html.slim
.container-fluid.navbar-menu
  nav.navbar.navbar-expand-lg.navbar-light.bg-light
    .col-md-10
      .ul.navbar-nav.mr-auto
        li class="nav-item"
          = link_to "HOME", root_path, class: "nav-link"
        li class="nav-item"
          = link_to "Questions", questions_path, class: "nav-link"
    .col-md-2.justify-content-center
      - if user_signed_in?
        = current_user.fullname
        =< current_user.email
        =< link_to t('links.navbar.logout'), destroy_user_session_path, method: :delete, class: "nav-link"
      - else
        =< link_to t('links.navbar.login'), new_user_session_path
        =< link_to 'SignUp', new_user_registration_path

app/views/shared/_search_form.html.slim
.row
  .col-md-12.text-right.mt-2
    .search-form.form-inline.float-right
      = form_tag("/search", method: "get", class: "form-inline") do
        = label_tag :query, ""
        .div class="input-group mb-2 mr-sm-2 mb-sm-0"
          = text_field_tag :query, params[:query], class: 'form-control', placeholder:"Search..."

        = select_tag(:resource, options_for_select(["Question", "Answer", "Comment", "User"], params[:resource]), prompt: "All", class: "custom-select mb-2 mr-sm-2 mb-sm-0" )
        = submit_tag "Search", class: "btn btn-info"

app/views/shared/_vote_links.html.slim
.vote_error
- if can?(:vote_count_up, resource ) && can?(:vote_count_down, resource)
  .vote_actions
    .vote
      = link_to image_tag("arrow_up.png", :border => 0, :alt => 'Vote UP!', :title => ''), polymorphic_path([:vote_count_up, resource]), class: 'vote_up_link', method: :post, remote: true
    |
    .vote
      = link_to image_tag("arrow_down.png", :border => 0, :alt => 'Vote Down!', :title => ''), polymorphic_path([:vote_count_down, resource]), class: 'vote_down_link', method: :post, remote: true