config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get :search, to: 'search#index'

  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}

  get 'comment/create'
  get 'comment/destroy'
  get 'comment/update'
  concern :votable do
    member do
      post :vote_count_up
      post :vote_count_down
    end
  end

  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end


  root to: "questions#index"
  resources :questions, concerns: [:votable, :commentable ] do
    resources :answers, concerns: [:votable, :commentable ], shallow: true do
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end

    end
  end

  resources :subscriptions, only: [:create, :destroy]
  resources :attachments, only: :destroy


  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Attachable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  validates :body, presence: true

  scope :best_ordered, -> { order(best: :desc) }

  after_create :notify

  def best!
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end



  def notify
    NotifySubscribersJob.perform_later(self)
  end

end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[destroy update best]
  after_action :publish_answer, only: :create

  respond_to :js

  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user_id: current_user.id)))
  end

  def destroy
    respond_with(@answer.destroy) if current_user.author?(@answer)
  end

  def update
    if current_user.author?(@answer)
      @answer.update(answer_params)
      respond_with(@answer)
    end
  end

  def best
    respond_with(@answer.best!)
  end

  private

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end

  def find_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def publish_answer
    ActionCable.server.broadcast(
        "question-#{@question.id}",
        answer: @answer,
        counter: @answer.votes_sum,
        attachments: @answer.attachments)
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_answer, only: :show
  before_action :find_question, only: [:index, :create]
  authorize_resource

  def index
    @answers = @question.answers
    respond_with @answers
  end

  def show
    respond_with @answer
  end

  def create
    @answer = Answer.create(answer_params.merge(user: current_resource_owner, question: @question))
    respond_with @answer
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.row.answer-block id="answer-#{answer.id}"
  .col-md-1.mt-4
    .vote_counter
      = answer.votes_sum
    .vote_links
      = render 'shared/vote_links', resource: answer

  div class="col-md-8 mt-4 #{ "best-answer" if answer&.best? }"
    - cache answer do
      p = answer.body
    = render 'shared/attachments', resource: answer unless answer.attachments.empty?

  .col-md-2.mt-4 id="actions"
    .btn-group-vertical
      - if answer.persisted? && can?(:best, answer)
        = link_to 'Best Answer', best_answer_path(answer), class: 'btn btn-outline-success btn-sm',  remote: true, method: :patch
      - if can?(:update, answer) && answer.persisted?
        = link_to 'Edit Answer', '', class: 'edit-answer-link btn btn-outline-secondary btn-sm', data: { answer_id: answer.id }
      - if can?(:destroy, answer) && answer.persisted?
        = link_to 'Delete Answer', answer, remote: true, method: :delete, class: 'delete-answer-link btn btn-outline-danger btn-sm', data: { answer_id: answer.id }


  div id="update-answer-form"
    - if  answer.persisted? && can?(:update, answer)
      = form_for answer, class: "edit_answer btn btn-danger", remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
        .form-group
          = f.label :body, 'Answer'
          = f.text_area :body, class: 'form-control'
        .form-group
          = f.submit 'Save', class: 'btn btn-primary'


  .col-md-12
    div class="comments_for_answer_#{answer.id} comments"
      - if can?(:create, Comment)
        = link_to 'Add Comment', '', class: "comment-link_for_answer_#{answer.id} comment-link btn btn-primary", data: {resource_id: answer.id, resource_type: "answer"}
        = render 'comments/form', resource: answer

      p Comments
      = render answer.comments
  .answer-info-block.ml-2
    p Answered by:  #{answer.user.fullname} at #{answer.created_at.to_formatted_s(:short) }

app/views/answers/best.js.erb
$('.best-answer').removeClass('best-answer');
$('#answer-<%= @answer.id %>').addClass('best-answer');
$('.answers').html("<%= j(render @answer.question.answers.best_ordered)  %>")

app/views/answers/create.js.erb
$('#error').remove();
<% if @answer.errors.any? %>
<% @answer.errors.full_messages.each do |message| %>
$('.errors').append('<div id="error"><%= j message %></div>');
<% end %>
<% else %>
$('.answers').append('<%= j render @answer %>');
$('input#answer_body').val("");
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/new.html.slim
= form_with model: [@question, @answer] do |form|
  = form.label :body
  = form.text_field :body
  = form.submit

app/views/answers/update.js.erb
$('#error').remove();
<% if @answer.errors.any? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answers').append('<div id="error"><%= j message %></div>');
  <% end %>
<% else %>
  $('form#edit-answer-'+<%= @answer.id %>).hide();
  $('#answer-'+<%= @answer.id %>).replaceWith('<%= j (render @answer) %>');
<% end %>