config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get :search, to: 'search#index'

  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}

  get 'comment/create'
  get 'comment/destroy'
  get 'comment/update'
  concern :votable do
    member do
      post :vote_count_up
      post :vote_count_down
    end
  end

  devise_scope :user do
    post '/register' => 'omniauth_callbacks#register'
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy, :update], shallow: true
  end


  root to: "questions#index"
  resources :questions, concerns: [:votable, :commentable ] do
    resources :answers, concerns: [:votable, :commentable ], shallow: true do
      patch :best, on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create], shallow: true do
        resources :answers, only: [:index, :show, :create]
      end

    end
  end

  resources :subscriptions, only: [:create, :destroy]
  resources :attachments, only: :destroy


  mount ActionCable.server => '/cable'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  authorize_resource
  respond_to :js

  def create
    @subscription = current_user.subscriptions.create(question_id: params[:question_id] )
    respond_with(@subscription)
  end

  def destroy
    subscription = Subscription.find(params[:id])
    @question = subscription.question
    respond_with(subscription.destroy)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_subscribe.html.slim
= link_to "Subscribe me!", subscriptions_path(question_id: @question.id), method: :post, remote: true, class: 'subscribe_question btn btn-info btn-sm'

app/views/subscriptions/_unsubscribe.html.slim
= link_to "Unsubscribe me!", subscription_path(subscription), class: 'btn btn-outline-info btn-sm', method: :delete, remote: true

app/views/subscriptions/create.js.erb
$('.subscriptions').html('<%= j render 'subscriptions/unsubscribe', subscription: @subscription %>');

app/views/subscriptions/destroy.js.erb
$('.subscriptions').html('<%= j render 'subscriptions/subscribe'%>');